#!/usr/bin/env node
// Deterministic pre-flight evidence for a review's target directory, run
// before Phase 1 dispatch and cited as evidence in the task packet both
// reviewer seats receive. Two tiers:
//
//   Tier 1 (metadata-only, always runs, no opt-in required): git diff, git
//   status, changed-file list -- pure inspection of the repository's own
//   state, no execution of anything the target repo defines.
//
//   Tier 2 (executable, requires --exec, off by default): runs commands the
//   CALLER supplies (e.g. the target's own test/lint/build command) through
//   the same filtered child environment codex-dispatch.mjs/
//   opencode-dispatch.mjs already use (env-filter.mjs), and binds each
//   result to a snapshot hash of the target's current git state (HEAD +
//   `git diff HEAD --binary` + a content hash per untracked file, the same
//   coverage opencode-dispatch.mjs's own computeSnapshotFingerprint already
//   uses for its worktree-reuse check) so a later content change -- tracked
//   OR untracked -- makes that evidence detectably stale rather than
//   silently reused.
//
// This script emits raw facts only -- command text, exit status, duration,
// stdout/stderr captured verbatim. **No interpretive text is generated by
// this script** -- enforced by construction, since there is no LLM call
// anywhere in this file.

import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';
import { buildChildEnv } from './env-filter.mjs';
import { hashInventory } from './snapshot-utils.mjs';
import { killTree } from './spawn-utils.mjs';

class RelayError extends Error {}

const DEFAULT_TIMEOUT_S = 1800;
const DEFAULT_TAIL_LINES = 20;
const MAX_MATCH_LINES = 50;
const MATCH_RE = /\b(fail(ed|ures?)?|errors?|not ok)\b|✖/i;
// Passing-test and zero-count summary lines, which often carry "error" or "fail" in a test name.
const PASS_LINE_RE = /^\s*(✔|ok\b|ℹ (pass|tests|suites|cancelled|skipped|todo|duration_ms|fail 0\b))/;

function isSignalLine(line) {
  return !PASS_LINE_RE.test(line) && MATCH_RE.test(line);
}

function printUsageAndExit(code) {
  process.stdout.write(USAGE);
  process.exit(code);
}

const USAGE = `preflight.mjs — deterministic pre-flight evidence for a review target.

Usage:
  node preflight.mjs --cd <path> [--exec "<command>"]... [--timeout <seconds>]
                 [--env-mode filtered|inherit] [--env-passthrough NAME,NAME]
                 [--out <path>] [--check-stale <snapshotHash>]
                 [--compact [--tail <lines>] [--log-dir <dir>]]

--cd <path>          Target directory. Required.
--exec "<command>"   Opt in to Tier 2: run this shell command against --cd. May
                     repeat -- each command runs independently against the SAME
                     snapshot hash captured once at the start of this invocation.
                     Without --exec, only Tier 1 (metadata-only) evidence is
                     produced -- this script NEVER executes anything the target
                     defines unless --exec explicitly names a command to run.
                     Runs through a filtered environment when --env-mode is
                     "filtered" (the default); --env-mode inherit passes the
                     full, unfiltered parent environment instead.
--timeout <seconds>  Per --exec command timeout. 0 means unlimited.
                     Default: 1800 (matches the dispatchers' own default).
--env-mode <mode>    "filtered" (default) or "inherit", same semantics as
                     codex-dispatch.mjs/opencode-dispatch.mjs.
--env-passthrough <names>  Comma-separated extra env var names to allow through
                     under --env-mode filtered.
--out <path>         Write the JSON result here instead of stdout.
--check-stale <hash>  Recompute --cd's CURRENT snapshot hash and report whether
                     it matches <hash> (typically a snapshotHash from a prior
                     preflight run's output). Prints {stale, currentSnapshotHash}
                     and exits 0 if it matches, 1 if it does not -- use this
                     before citing old Tier 2 evidence as EXECUTED basis for a
                     live review. When given, no other tier runs; this flag is
                     standalone.
--compact            Keep the result small enough to inline in a task packet:
                     each command's full stdout/stderr, and the Tier 1 git diff,
                     go to files under --log-dir, and the JSON keeps byte counts,
                     sha256, the last --tail lines, and every line matching
                     fail/error/not ok that is not a passing-test line (capped at
                     ${MAX_MATCH_LINES}). The log files are the raw evidence to cite; the
                     sha256 proves a log was not edited.
--tail <lines>       Lines of each stream kept in the JSON with --compact.
                     Default: ${DEFAULT_TAIL_LINES}.
--log-dir <dir>      Where --compact writes the full logs. Default: "<--out>.logs"
                     when --out is given; required otherwise.
-h, --help           Print this message and exit 0.

Output (normal run, no --check-stale): { tier1: {...}, tier2: {...} | null,
snapshotHash: string }. For a git repository the hash covers HEAD, the binary
diff against HEAD, and untracked file contents. For a plain directory it is a
content-hash inventory of every file (skipping .git/ and node_modules/), and
tier1 reports gitRepo:false with the file count. No interpretive text is ever
generated -- only raw command/exit/output facts.
`;

function parseArgs(argv) {
  const args = {
    cd: null,
    exec: [],
    timeout: DEFAULT_TIMEOUT_S,
    envMode: 'filtered',
    envPassthrough: [],
    out: null,
    checkStale: null,
    compact: false,
    tail: DEFAULT_TAIL_LINES,
    logDir: null,
  };
  for (let i = 0; i < argv.length; i++) {
    const tok = argv[i];
    const takeValue = () => {
      const v = argv[++i];
      if (v === undefined || v.startsWith('--')) throw new RelayError(`${tok} requires a value`);
      return v;
    };
    if (tok === '--cd') args.cd = takeValue();
    else if (tok === '--exec') args.exec.push(takeValue());
    else if (tok === '--timeout') {
      const v = takeValue();
      if (!/^[0-9]+$/.test(v)) throw new RelayError('--timeout must be a whole number of seconds, 0 for unlimited');
      args.timeout = Number(v);
    } else if (tok === '--env-mode') args.envMode = takeValue();
    else if (tok === '--env-passthrough') args.envPassthrough = takeValue().split(',').map((s) => s.trim()).filter(Boolean);
    else if (tok === '--out') args.out = takeValue();
    else if (tok === '--check-stale') args.checkStale = takeValue();
    else if (tok === '--compact') args.compact = true;
    else if (tok === '--tail') {
      const v = takeValue();
      if (!/^[0-9]+$/.test(v)) throw new RelayError('--tail must be a whole number of lines');
      args.tail = Number(v);
    } else if (tok === '--log-dir') args.logDir = takeValue();
    else if (tok === '-h' || tok === '--help') printUsageAndExit(0);
    else throw new RelayError(`unrecognized argument: ${tok}`);
  }
  if (!args.cd) throw new RelayError('--cd <path> is required');
  if (args.compact && !args.logDir) {
    if (!args.out) throw new RelayError('--compact needs --log-dir (or --out, which defaults it to "<--out>.logs")');
    args.logDir = `${args.out}.logs`;
  }
  if (args.envMode !== 'filtered' && args.envMode !== 'inherit') {
    throw new RelayError('--env-mode must be "filtered" or "inherit"');
  }
  for (const name of args.envPassthrough) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      throw new RelayError(`--env-passthrough: "${name}" is not a valid environment variable name`);
    }
  }
  return args;
}

// git is invoked directly (structured argv, shell:false, no shell metachar
// risk from a repo path) -- this is NOT the Tier 2 --exec path, which needs
// a real shell to interpret an arbitrary caller-supplied command string; see
// runWithTimeout below for that.
function runCapture(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, shell: false });
    let stdout = Buffer.alloc(0);
    let stderr = Buffer.alloc(0);
    child.stdout.on('data', (d) => { stdout = Buffer.concat([stdout, d]); });
    child.stderr.on('data', (d) => { stderr = Buffer.concat([stderr, d]); });
    child.on('error', reject);
    child.on('close', (code) => resolve({ code, stdout, stderr }));
  });
}

async function isGitRepo(cwd) {
  const result = await runCapture('git', ['rev-parse', '--is-inside-work-tree'], cwd);
  return result.code === 0 && result.stdout.toString('utf8').trim() === 'true';
}

// Tier 1: pure repository-state inspection, no execution of anything the
// target repo defines. Runs unconditionally, no opt-in required.
async function runTier1(cd) {
  const gitTracked = await isGitRepo(cd);
  if (!gitTracked) {
    const inventory = await hashInventory(cd);
    return {
      gitRepo: false,
      fileCount: Object.keys(inventory.files).length,
      note: `"${cd}" is not a git repository; diff/status evidence is unavailable, and snapshotHash is a content-hash inventory of every file (skipping .git/ and node_modules/)`,
    };
  }
  // git diff HEAD (not bare `git diff`, working-tree-vs-index only) so
  // STAGED changes are included too -- a review target commonly has staged
  // work, and a bare `git diff` would silently omit it. changedFiles/
  // fileStats include untracked files as well, matching computeSnapshotHash's
  // own coverage below (HEAD diff + untracked content). --relative on both
  // diff calls makes their paths cd-relative, matching git status/ls-files
  // (already cwd-relative) and the stat(path.join(cd, rel)) calls below --
  // without it, a cd pointed at a subdirectory would produce root-relative
  // diff paths that never match, silently dropping every tracked change
  // from fileStats.
  const [diff, status, nameOnly, untrackedNames] = await Promise.all([
    runCapture('git', ['diff', '--relative', 'HEAD'], cd),
    runCapture('git', ['status', '--porcelain'], cd),
    runCapture('git', ['diff', '--relative', 'HEAD', '--name-only'], cd),
    runCapture('git', ['ls-files', '--others', '--exclude-standard'], cd),
  ]);
  const trackedChanged = nameOnly.stdout.toString('utf8').split('\n').map((l) => l.trim()).filter(Boolean);
  const untracked = untrackedNames.stdout.toString('utf8').split('\n').map((l) => l.trim()).filter(Boolean);
  const changedFiles = [...new Set([...trackedChanged, ...untracked])];
  const fileStats = {};
  for (const rel of changedFiles) {
    try {
      const s = await stat(path.join(cd, rel));
      fileStats[rel] = { sizeBytes: s.size, mtime: s.mtime.toISOString() };
    } catch {
      // File deleted in the working tree relative to the index -- no stat
      // available; omit rather than fabricate a size/mtime for a path that
      // no longer exists.
    }
  }
  return {
    gitRepo: true,
    diff: diff.stdout.toString('utf8'),
    status: status.stdout.toString('utf8'),
    changedFiles,
    fileStats,
  };
}

function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

function sha256OfFile(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256');
    const stream = createReadStream(filePath);
    stream.on('data', (chunk) => hash.update(chunk));
    stream.on('error', reject);
    stream.on('end', () => resolve(hash.digest('hex')));
  });
}

// Matches opencode-dispatch.mjs's computeSnapshotFingerprint coverage: HEAD +
// `git diff HEAD --binary` (so a binary file change is distinguishable, not
// collapsed to the same "Binary files differ" text every time) + a content
// hash per untracked file (so a Phase 1 seat CREATING a new file, not just
// editing a tracked one, is also detected as a state change). This is a
// separate implementation from opencode-dispatch.mjs's private
// computeSnapshotFingerprint (not exported there), but deliberately matches
// its exact input coverage.
async function computeSnapshotHash(cd) {
  if (!(await isGitRepo(cd))) return (await hashInventory(cd)).snapshotHash;
  const headRes = await runCapture('git', ['rev-parse', 'HEAD'], cd);
  if (headRes.code !== 0) {
    throw new RelayError(`could not resolve HEAD in "${cd}" (not a git repo, or no commits yet)`);
  }
  const diffRes = await runCapture('git', ['diff', 'HEAD', '--binary'], cd);
  const untrackedRes = await runCapture('git', ['ls-files', '--others', '--exclude-standard', '-z'], cd);
  const rawUntracked = untrackedRes.stdout.toString('utf8').split('\0').filter((p) => p.length > 0);
  const untrackedPaths = rawUntracked.filter((p) => !p.endsWith('/')).sort();

  const hash = createHash('sha256');
  hash.update(headRes.stdout.toString('utf8').trim());
  hash.update('\n');
  hash.update(diffRes.stdout);
  for (const rel of untrackedPaths) {
    hash.update('\n');
    hash.update(rel);
    hash.update(':');
    hash.update(await sha256OfFile(path.join(cd, rel)));
  }
  return hash.digest('hex');
}

// Tier 2's --exec command is an arbitrary caller-supplied shell command
// string (e.g. "npm test", "pytest -q && echo done"), so this genuinely
// needs `shell: true` on both platforms to be interpreted at all -- unlike
// codex-dispatch.mjs/opencode-dispatch.mjs's spawnCli, which only ever
// invokes a known executable (codex/opencode) with structured argv and
// therefore uses shell:true JUST for win32's .cmd-shim resolution. killTree
// (from spawn-utils.mjs) still applies for the timeout-kill path: on win32
// it uses taskkill /T against the whole process tree (the same reason
// codex-dispatch.mjs/opencode-dispatch.mjs need it -- a plain child.kill()
// only terminates cmd.exe, orphaning the real process underneath).
// spawnFn/platform overridable so tests can assert detached:true on the POSIX branch without
// needing to actually run on POSIX (same seam spawn-utils.mjs's spawnCli uses).
function runWithTimeout(command, { cd, env, timeout }, { spawnFn = spawn, platform = process.platform } = {}) {
  return new Promise((resolve, reject) => {
    // detached:true makes the shell the leader of its own POSIX process group, which is what
    // lets killTree's process.kill(-pid) below reach the whole tree instead of failing ESRCH
    // against a group the child was never actually the leader of.
    const child = spawnFn(command, { cwd: cd, env, shell: true, detached: platform !== 'win32' });
    let stdout = '';
    let stderr = '';
    let settled = false;
    let timer = null;
    // Set BEFORE calling killTree, not inside its .finally(): killTree's own
    // taskkill (win32) or SIGTERM/SIGKILL (POSIX) terminating the child fires
    // this same promise's 'close' event, which races against killTree's own
    // resolution. Flipping timedOut here first means 'close' below always
    // sees timedOut:true once the timer has fired, regardless of which
    // callback's resolve() actually wins that race.
    let timedOut = false;
    if (timeout) {
      timer = setTimeout(() => {
        timedOut = true;
        killTree(child).finally(() => {
          if (settled) return;
          settled = true;
          resolve({ code: null, stdout, stderr, timedOut: true });
        });
      }, timeout * 1000);
    }
    child.stdout.on('data', (d) => { stdout += d.toString('utf8'); });
    child.stderr.on('data', (d) => { stderr += d.toString('utf8'); });
    child.on('error', (err) => {
      if (timer) clearTimeout(timer);
      if (settled) return;
      settled = true;
      reject(err);
    });
    child.on('close', (code) => {
      if (timer) clearTimeout(timer);
      if (settled) return;
      settled = true;
      resolve({ code: timedOut ? null : code, stdout, stderr, timedOut });
    });
  });
}

// Tier 2: executes caller-supplied commands (the target's own test/lint/
// build command) through a filtered child environment. Every command in
// this call is bound to the SAME snapshotHash, captured once before the
// first command runs.
async function runTier2({ cd, commands, timeout, envMode, envPassthrough }, spawnOpts = {}) {
  const snapshotHash = await computeSnapshotHash(cd);
  const env = buildChildEnv({ envMode, envPassthrough });
  const results = [];
  for (const command of commands) {
    const startedAt = new Date().toISOString();
    const startedAtMs = Date.now();
    const result = await runWithTimeout(command, { cd, env, timeout }, spawnOpts);
    results.push({
      command,
      startedAt,
      finishedAt: new Date().toISOString(),
      durationMs: Date.now() - startedAtMs,
      exitCode: result.code,
      timedOut: result.timedOut,
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
  return { snapshotHash, results };
}

// Re-checks whether a previously-captured snapshotHash still matches the
// target's CURRENT state. A caller uses this before citing old Tier 2 (or
// Tier 1) evidence as current -- stale evidence must never be presented as
// describing content it no longer describes. Never mutates or interprets
// the evidence; only reports match/mismatch as a fact.
async function checkStale(cd, snapshotHash) {
  const current = await computeSnapshotHash(cd);
  return { stale: current !== snapshotHash, currentSnapshotHash: current };
}

async function run(args) {
  const cdAbs = path.resolve(args.cd);
  let cdStat;
  try {
    cdStat = await stat(cdAbs);
  } catch (err) {
    throw new RelayError(`--cd "${cdAbs}" does not exist or is not accessible: ${err.message}`);
  }
  if (!cdStat.isDirectory()) {
    throw new RelayError(`--cd "${cdAbs}" is not a directory`);
  }

  const tier1 = await runTier1(cdAbs);

  let snapshotHash = await computeSnapshotHash(cdAbs);
  let tier2 = null;
  if (args.exec.length > 0) {
    tier2 = await runTier2({
      cd: cdAbs,
      commands: args.exec,
      timeout: args.timeout,
      envMode: args.envMode,
      envPassthrough: args.envPassthrough,
    });
    // Tier 1 and Tier 2 are computed from the same pre-command git state in
    // a single invocation (Tier 1 runs, then Tier 2's own snapshotHash is
    // captured immediately before its first --exec command) -- both must
    // agree, since nothing in this process mutates the target between them.
    snapshotHash = tier2.snapshotHash;
    if (args.compact) tier2 = await compactTier2(tier2, args);
  }

  return { tier1: args.compact ? await compactTier1(tier1, args) : tier1, tier2, snapshotHash };
}

// The Tier 1 diff can be as large as the whole change under review; seats read it from the log or git.
async function compactTier1(tier1, { logDir }) {
  if (!tier1.gitRepo) return tier1;
  const dir = path.resolve(logDir);
  await mkdir(dir, { recursive: true });
  const diffLog = path.join(dir, 'tier1.diff');
  await writeFile(diffLog, tier1.diff, 'utf8');
  const { diff, ...rest } = tier1;
  return {
    ...rest,
    diff: { bytes: Buffer.byteLength(diff, 'utf8'), sha256: sha256(Buffer.from(diff, 'utf8')), log: diffLog },
  };
}

function streamSummary(text, tailLines) {
  const lines = text.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  const matches = lines.filter(isSignalLine);
  return {
    bytes: Buffer.byteLength(text, 'utf8'),
    sha256: sha256(Buffer.from(text, 'utf8')),
    lineCount: lines.length,
    tail: tailLines > 0 ? lines.slice(-tailLines) : [],
    matches: matches.slice(0, MAX_MATCH_LINES),
    matchesTruncated: matches.length > MAX_MATCH_LINES,
  };
}

// Full streams go to --log-dir; the JSON keeps only what a reader needs to judge and verify them.
async function compactTier2(tier2, { logDir, tail }) {
  const dir = path.resolve(logDir);
  await mkdir(dir, { recursive: true });
  const results = [];
  for (const [i, r] of tier2.results.entries()) {
    const stdoutLog = path.join(dir, `command-${i + 1}.stdout.log`);
    const stderrLog = path.join(dir, `command-${i + 1}.stderr.log`);
    await writeFile(stdoutLog, r.stdout, 'utf8');
    await writeFile(stderrLog, r.stderr, 'utf8');
    const { stdout, stderr, ...rest } = r;
    results.push({
      ...rest,
      stdout: { ...streamSummary(stdout, tail), log: stdoutLog },
      stderr: { ...streamSummary(stderr, tail), log: stderrLog },
    });
  }
  return { snapshotHash: tier2.snapshotHash, compact: true, results };
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0) printUsageAndExit(0);
  let args;
  try {
    args = parseArgs(argv);
  } catch (err) {
    if (err instanceof RelayError) {
      process.stderr.write(`preflight.mjs: ${err.message}\n\n`);
      printUsageAndExit(2);
    }
    throw err;
  }
  try {
    if (args.checkStale !== null) {
      const cdAbs = path.resolve(args.cd);
      const result = await checkStale(cdAbs, args.checkStale);
      process.stdout.write(JSON.stringify(result, null, 2) + '\n');
      process.exit(result.stale ? 1 : 0);
    }
    const result = await run(args);
    const text = JSON.stringify(result, null, 2) + '\n';
    if (args.out) {
      await writeFile(args.out, text, 'utf8');
    } else {
      process.stdout.write(text);
    }
  } catch (err) {
    if (err instanceof RelayError) {
      process.stderr.write(`preflight.mjs: ${err.message}\n`);
      process.exit(1);
    }
    throw err;
  }
}

const isDirectRun =
  typeof process.argv[1] === 'string' &&
  import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) {
  main().catch((err) => {
    process.stderr.write(`preflight.mjs: unexpected failure: ${err.stack || err}\n`);
    process.exit(1);
  });
}

export { parseArgs, runTier1, runTier2, computeSnapshotHash, checkStale, run, compactTier2, RelayError, runCapture, isGitRepo };
