#!/usr/bin/env node
// Deterministic pre-flight evidence for a review's target directory, run
// before Phase 1 dispatch and cited as evidence in the task packet both
// reviewer seats receive. Two tiers:
//
//   Tier 1 (metadata-only, always runs, no opt-in required): git diff, git
//   status, changed-file list -- pure inspection of the repository's own
//   state, no execution of anything the target repo defines.
//
//   Tier 2 (executable, requires --exec, off by default): runs commands the
//   CALLER supplies (e.g. the target's own test/lint/build command) through
//   the same filtered child environment codex-dispatch.mjs/
//   opencode-dispatch.mjs already use (env-filter.mjs), and binds each
//   result to a snapshot hash of the target's current git state (HEAD +
//   `git diff HEAD --binary` + a content hash per untracked file, the same
//   coverage opencode-dispatch.mjs's own computeSnapshotFingerprint already
//   uses for its worktree-reuse check) so a later content change -- tracked
//   OR untracked -- makes that evidence detectably stale rather than
//   silently reused.
//
// This script emits raw facts only -- command text, exit status, duration,
// stdout/stderr captured verbatim. **No interpretive text is generated by
// this script** -- enforced by construction, since there is no LLM call
// anywhere in this file.

import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';
import { buildChildEnv } from './env-filter.mjs';
import { diffInventories, hashInventory } from './snapshot-utils.mjs';
import { killTree } from './spawn-utils.mjs';

class RelayError extends Error {}

const DEFAULT_TIMEOUT_S = 1800;
const DEFAULT_TAIL_LINES = 20;
const MAX_MATCH_LINES = 50;
const MATCH_RE = /\b(fail(ed|ures?)?|errors?|not ok)\b|✖/i;
// Passing-test and zero-count summary lines, which often carry "error" or "fail" in a test name.
const PASS_LINE_RE = /^\s*(✔|ok\b|ℹ (pass|tests|suites|cancelled|skipped|todo|duration_ms|fail 0\b))/;
// Test-runner totals (node:test, pytest, mocha/jest, TAP), kept even when they fall outside --tail.
// pytest -q prints its total bare ("137 passed, 1 warning in 0.37s"), without the "=====" wrapper.
const SUMMARY_RE = /^\s*(ℹ (tests|pass|fail) \d+|=+ .*\b\d+ (passed|failed|errors?)\b.*=+|\d+ (passed|failed|errors?|skipped|xfailed|xpassed|deselected)\b[^=\n]*\bin \d+(\.\d+)?s\b|\d+ (passing|failing|pending)\b|Tests?:\s+.*\d+ (passed|failed|total)|# (tests|pass|fail) \d+)/i;

function isSignalLine(line) {
  return !PASS_LINE_RE.test(line) && MATCH_RE.test(line);
}

function printUsageAndExit(code) {
  process.stdout.write(USAGE);
  process.exit(code);
}

const USAGE = `preflight.mjs — deterministic pre-flight evidence for a review target.

Usage:
  node preflight.mjs --cd <path> [--exec "<command>"]... [--timeout <seconds>]
                 [--env-mode filtered|inherit] [--env-passthrough NAME,NAME]
                 [--out <path>] [--check-stale <snapshotHash>]
                 [--compact [--tail <lines>] [--log-dir <dir>]]
                 [--repo <path>]... [--fetch] [--watch-file <path>]...
                 [--source-snapshot <folder>=<repo>@<ref>]...

--cd <path>          Target directory. Required.
--exec "<command>"   Opt in to Tier 2: run this shell command against --cd. May
                     repeat -- each command runs independently against the SAME
                     snapshot hash captured once at the start of this invocation.
                     Without --exec, only Tier 1 (metadata-only) evidence is
                     produced -- this script NEVER executes anything the target
                     defines unless --exec explicitly names a command to run.
                     Runs through a filtered environment when --env-mode is
                     "filtered" (the default); --env-mode inherit passes the
                     full, unfiltered parent environment instead.
--timeout <seconds>  Per --exec command timeout. 0 means unlimited.
                     Default: 1800 (matches the dispatchers' own default).
--env-mode <mode>    "filtered" (default) or "inherit", same semantics as
                     codex-dispatch.mjs/opencode-dispatch.mjs.
--env-passthrough <names>  Comma-separated extra env var names to allow through
                     under --env-mode filtered.
--out <path>         Write the JSON result here instead of stdout.
--check-stale <hash>  Recompute --cd's CURRENT snapshot hash and report whether
                     it matches <hash> (typically a snapshotHash from a prior
                     preflight run's output). Prints {stale, currentSnapshotHash}
                     and exits 0 if it matches, 1 if it does not -- use this
                     before citing old Tier 2 evidence as EXECUTED basis for a
                     live review. When given, no other tier runs; this flag is
                     standalone.
--compact            Keep the result small enough to inline in a task packet:
                     each command's full stdout/stderr, and the Tier 1 git diff,
                     go to files under --log-dir, and the JSON keeps byte counts,
                     sha256, the last --tail lines, and every line matching
                     fail/error/not ok that is not a passing-test line (capped at
                     ${MAX_MATCH_LINES}). The log files are the raw evidence to cite; the
                     sha256 proves a log was not edited.
--tail <lines>       Lines of each stream kept in the JSON with --compact.
                     Default: ${DEFAULT_TAIL_LINES}.
--log-dir <dir>      Where --compact writes the full logs. Default: "<--out>.logs"
                     when --out is given; required otherwise. A rerun into the same
                     folder first deletes this script's own earlier logs
                     (command-<n>.stdout/stderr.log, tier1.diff; listed in
                     "clearedEarlierLogs") and leaves every other file alone, so
                     a bad --exec can be rerun in place.
--repo <path>        Another repository the task packet reviews by path (may
                     repeat). Gets the same freshness record as --cd in "repos";
                     it is not part of snapshotHash and runs no Tier 2 command.
--source-snapshot <folder>=<repo>@<ref>
                     A plain export of another repository (git archive, a
                     downloaded tarball) the packet reviews (may repeat). It has
                     no git metadata, so "sourceSnapshots" records the stated repo
                     and ref as given, plus the folder's file count and
                     content-hash snapshotHash, which pins the bytes reviewed.
                     Python caches (__pycache__/, .pytest_cache/, *.pyc, *.pyo)
                     are left out of the count and hash and listed in
                     skippedCacheCount/skippedCaches (first 20), with a WARNING.
--fetch              Run "git fetch" in --cd and each --repo first, so behind
                     counts compare against the remote as it is now. Contacts the
                     network with the caller's own git credentials (no prompt:
                     GIT_TERMINAL_PROMPT=0), 120 s limit per repo. Without it the
                     counts use the last fetch; lastFetchedAt says when that was.
--watch-file <path>  A file the task packet names (may repeat; relative to the
                     current directory or absolute). For the --cd/--repo that
                     holds it, "watchedChangedUpstream" lists it with the number
                     of commits on the upstream or origin/HEAD, not yet in HEAD,
                     that change it, and contentDiffers (does the file there
                     differ from HEAD). stderr prints a WARNING when it differs,
                     and a "note" when only the commits differ (the same change
                     reached HEAD another way). A file inside none of them is
                     listed in "watchFilesOutsideRepos". A repos entry has no
                     watchedChangedUpstream field when no --watch-file lies in
                     that repository, and [] when its files have no upstream
                     changes.
-h, --help           Print this message and exit 0.

Output (normal run, no --check-stale): { tier1: {...}, tier2: {...} | null,
snapshotHash: string }. For a git repository the hash covers only the --cd
folder: its committed tree, its binary diff against HEAD, and its untracked
file contents, so changes elsewhere in a monorepo do not make it stale. For a
plain directory it is a content-hash inventory of every file (skipping .git/
and node_modules/), and tier1 reports gitRepo:false with the file count.
tier2 also reports snapshotHashAfter and targetChanged, and each command's
touchedFiles: files under --cd it created, changed, or deleted (gitignored
output is not covered). A test suite that writes into the target before the
seats start shows up here. No interpretive text is ever generated -- only raw
command/exit/output facts.

repos: one freshness record for --cd, then one per --repo: branch, head,
headDate, dirty, upstream, ahead/behind against it, defaultBranch
(origin/HEAD) and behindDefault, lastFetchedAt, fetched. A plain directory
gets {gitRepo:false}; a missing upstream or origin/HEAD gives null counts. A
repo behind its upstream or default branch also prints "preflight: WARNING:
<path> is <n> commit(s) behind <ref>" on stderr. Remote URLs are never
recorded (they can carry credentials). Each record also gets
reviewArtifactCount/reviewArtifactFiles (first 50) when files there hold
review output with real claim IDs: a "# Seat A findings" header, a claim
heading written "## A1 — ..." together with a "Severity:" line, or a JSON file
with both "origins": ["A1"...] and "final_state". The protocol's own schema
example (a file starting "# Shared Review Protocol") is skipped. Reading stops
once 50 such files are found (reviewArtifactCountIsLowerBound); with no such
file the three fields are absent, not empty. The scan
treats target text as safe, so such files could hide a real claim-ID leak;
stderr warns.
`;

function parseArgs(argv) {
  const args = {
    cd: null,
    exec: [],
    timeout: DEFAULT_TIMEOUT_S,
    envMode: 'filtered',
    envPassthrough: [],
    out: null,
    checkStale: null,
    compact: false,
    tail: DEFAULT_TAIL_LINES,
    logDir: null,
    repos: [],
    fetch: false,
    watchFiles: [],
    sourceSnapshots: [],
  };
  for (let i = 0; i < argv.length; i++) {
    const tok = argv[i];
    const takeValue = () => {
      const v = argv[++i];
      if (v === undefined || v.startsWith('--')) throw new RelayError(`${tok} requires a value`);
      return v;
    };
    if (tok === '--cd') args.cd = takeValue();
    else if (tok === '--exec') args.exec.push(takeValue());
    else if (tok === '--timeout') {
      const v = takeValue();
      if (!/^[0-9]+$/.test(v)) throw new RelayError('--timeout must be a whole number of seconds, 0 for unlimited');
      args.timeout = Number(v);
    } else if (tok === '--env-mode') args.envMode = takeValue();
    else if (tok === '--env-passthrough') args.envPassthrough = takeValue().split(',').map((s) => s.trim()).filter(Boolean);
    else if (tok === '--out') args.out = takeValue();
    else if (tok === '--check-stale') args.checkStale = takeValue();
    else if (tok === '--compact') args.compact = true;
    else if (tok === '--tail') {
      const v = takeValue();
      if (!/^[0-9]+$/.test(v)) throw new RelayError('--tail must be a whole number of lines');
      args.tail = Number(v);
    } else if (tok === '--log-dir') args.logDir = takeValue();
    else if (tok === '--repo') args.repos.push(takeValue());
    else if (tok === '--source-snapshot') {
      const v = takeValue();
      // <dir>=<repo>@<ref>: the last "@" splits repo from ref, the first "=" splits the folder off.
      const m = /^(.+?)=(.+)@([^@\s]+)$/.exec(v);
      if (!m || m[2].trim() === '') throw new RelayError(`--source-snapshot "${v}" must look like <folder>=<repo>@<commit or tag>, with no spaces in the ref, for example exports/svc=org/svc@b45981e`);
      args.sourceSnapshots.push({ dir: m[1], repo: m[2], ref: m[3] });
    }
    else if (tok === '--fetch') args.fetch = true;
    else if (tok === '--watch-file') args.watchFiles.push(takeValue());
    else if (tok === '-h' || tok === '--help') printUsageAndExit(0);
    else throw new RelayError(`unrecognized argument: ${tok}`);
  }
  if (!args.cd) throw new RelayError('--cd <path> is required');
  if (args.compact && !args.logDir) {
    if (!args.out) throw new RelayError('--compact needs --log-dir (or --out, which defaults it to "<--out>.logs")');
    args.logDir = `${args.out}.logs`;
  }
  if (args.envMode !== 'filtered' && args.envMode !== 'inherit') {
    throw new RelayError('--env-mode must be "filtered" or "inherit"');
  }
  for (const name of args.envPassthrough) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      throw new RelayError(`--env-passthrough: "${name}" is not a valid environment variable name`);
    }
  }
  return args;
}

// git is invoked directly (structured argv, shell:false, no shell metachar
// risk from a repo path) -- this is NOT the Tier 2 --exec path, which needs
// a real shell to interpret an arbitrary caller-supplied command string; see
// runWithTimeout below for that.
function runCapture(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, shell: false });
    let stdout = Buffer.alloc(0);
    let stderr = Buffer.alloc(0);
    child.stdout.on('data', (d) => { stdout = Buffer.concat([stdout, d]); });
    child.stderr.on('data', (d) => { stderr = Buffer.concat([stderr, d]); });
    child.on('error', reject);
    child.on('close', (code) => resolve({ code, stdout, stderr }));
  });
}

async function isGitRepo(cwd) {
  const result = await runCapture('git', ['rev-parse', '--is-inside-work-tree'], cwd);
  return result.code === 0 && result.stdout.toString('utf8').trim() === 'true';
}

// Tier 1: pure repository-state inspection, no execution of anything the
// target repo defines. Runs unconditionally, no opt-in required.
// inventory: an already computed hashInventory(cd) for a plain folder, so run() hashes it once.
async function runTier1(cd, inventory = null) {
  const gitTracked = await isGitRepo(cd);
  if (!gitTracked) {
    inventory ??= await hashInventory(cd);
    return {
      gitRepo: false,
      fileCount: Object.keys(inventory.files).length,
      note: `"${cd}" is not a git repository; diff/status evidence is unavailable, and snapshotHash is a content-hash inventory of every file (skipping .git/ and node_modules/)`,
    };
  }
  // git diff HEAD (not bare `git diff`, working-tree-vs-index only) so
  // STAGED changes are included too -- a review target commonly has staged
  // work, and a bare `git diff` would silently omit it. changedFiles/
  // fileStats include untracked files as well, matching computeSnapshotHash's
  // own coverage below (HEAD diff + untracked content). --relative on both
  // diff calls makes their paths cd-relative, matching git status/ls-files
  // (already cwd-relative) and the stat(path.join(cd, rel)) calls below --
  // without it, a cd pointed at a subdirectory would produce root-relative
  // diff paths that never match, silently dropping every tracked change
  // from fileStats.
  const [diff, status, nameOnly, untrackedNames] = await Promise.all([
    runCapture('git', ['diff', '--relative', 'HEAD'], cd),
    runCapture('git', ['status', '--porcelain'], cd),
    runCapture('git', ['diff', '--relative', 'HEAD', '--name-only'], cd),
    runCapture('git', ['ls-files', '--others', '--exclude-standard'], cd),
  ]);
  const trackedChanged = nameOnly.stdout.toString('utf8').split('\n').map((l) => l.trim()).filter(Boolean);
  const untracked = untrackedNames.stdout.toString('utf8').split('\n').map((l) => l.trim()).filter(Boolean);
  const changedFiles = [...new Set([...trackedChanged, ...untracked])];
  const fileStats = {};
  for (const rel of changedFiles) {
    try {
      const s = await stat(path.join(cd, rel));
      fileStats[rel] = { sizeBytes: s.size, mtime: s.mtime.toISOString() };
    } catch {
      // File deleted in the working tree relative to the index -- no stat
      // available; omit rather than fabricate a size/mtime for a path that
      // no longer exists.
    }
  }
  return {
    gitRepo: true,
    diff: diff.stdout.toString('utf8'),
    status: status.stdout.toString('utf8'),
    changedFiles,
    fileStats,
  };
}

function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

function sha256OfFile(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256');
    const stream = createReadStream(filePath);
    stream.on('data', (chunk) => hash.update(chunk));
    stream.on('error', reject);
    stream.on('end', () => resolve(hash.digest('hex')));
  });
}

// Scoped to --cd: the committed tree of that folder, its binary diff against HEAD (so a binary
// change is distinguishable), and a content hash per untracked file (so a created file counts).
// A commit or edit elsewhere in a monorepo does not make this target's evidence stale.
async function computeSnapshotHash(cd, inventory = null) {
  if (!(await isGitRepo(cd))) return (inventory ?? (await hashInventory(cd))).snapshotHash;
  const headRes = await runCapture('git', ['rev-parse', 'HEAD'], cd);
  if (headRes.code !== 0) {
    throw new RelayError(`could not resolve HEAD in "${cd}" (not a git repo, or no commits yet)`);
  }
  const prefix = (await runCapture('git', ['rev-parse', '--show-prefix'], cd)).stdout.toString('utf8').trim();
  const treeRes = await runCapture('git', ['rev-parse', `HEAD:${prefix}`], cd);
  // A folder that exists only in the working tree has no committed tree yet.
  const treeId = treeRes.code === 0 ? treeRes.stdout.toString('utf8').trim() : 'no-committed-tree';
  const diffRes = await runCapture('git', ['diff', 'HEAD', '--binary', '--relative', '--', '.'], cd);
  const untrackedRes = await runCapture('git', ['ls-files', '--others', '--exclude-standard', '-z'], cd);
  const rawUntracked = untrackedRes.stdout.toString('utf8').split('\0').filter((p) => p.length > 0);
  const untrackedPaths = rawUntracked.filter((p) => !p.endsWith('/')).sort();

  const hash = createHash('sha256');
  hash.update(treeId);
  hash.update('\n');
  hash.update(diffRes.stdout);
  for (const rel of untrackedPaths) {
    hash.update('\n');
    hash.update(rel);
    hash.update(':');
    hash.update(await sha256OfFile(path.join(cd, rel)));
  }
  return hash.digest('hex');
}

// Tier 2's --exec command is an arbitrary caller-supplied shell command
// string (e.g. "npm test", "pytest -q && echo done"), so this genuinely
// needs `shell: true` on both platforms to be interpreted at all -- unlike
// codex-dispatch.mjs/opencode-dispatch.mjs's spawnCli, which only ever
// invokes a known executable (codex/opencode) with structured argv and
// therefore uses shell:true JUST for win32's .cmd-shim resolution. killTree
// (from spawn-utils.mjs) still applies for the timeout-kill path: on win32
// it uses taskkill /T against the whole process tree (the same reason
// codex-dispatch.mjs/opencode-dispatch.mjs need it -- a plain child.kill()
// only terminates cmd.exe, orphaning the real process underneath).
// spawnFn/platform overridable so tests can assert detached:true on the POSIX branch without
// needing to actually run on POSIX (same seam spawn-utils.mjs's spawnCli uses).
function runWithTimeout(command, { cd, env, timeout }, { spawnFn = spawn, platform = process.platform } = {}) {
  return new Promise((resolve, reject) => {
    // detached:true makes the shell the leader of its own POSIX process group, which is what
    // lets killTree's process.kill(-pid) below reach the whole tree instead of failing ESRCH
    // against a group the child was never actually the leader of.
    const child = spawnFn(command, { cwd: cd, env, shell: true, detached: platform !== 'win32' });
    let stdout = '';
    let stderr = '';
    let settled = false;
    let timer = null;
    // Set BEFORE calling killTree, not inside its .finally(): killTree's own
    // taskkill (win32) or SIGTERM/SIGKILL (POSIX) terminating the child fires
    // this same promise's 'close' event, which races against killTree's own
    // resolution. Flipping timedOut here first means 'close' below always
    // sees timedOut:true once the timer has fired, regardless of which
    // callback's resolve() actually wins that race.
    let timedOut = false;
    if (timeout) {
      timer = setTimeout(() => {
        timedOut = true;
        killTree(child).finally(() => {
          if (settled) return;
          settled = true;
          resolve({ code: null, stdout, stderr, timedOut: true });
        });
      }, timeout * 1000);
    }
    child.stdout.on('data', (d) => { stdout += d.toString('utf8'); });
    child.stderr.on('data', (d) => { stderr += d.toString('utf8'); });
    child.on('error', (err) => {
      if (timer) clearTimeout(timer);
      if (settled) return;
      settled = true;
      reject(err);
    });
    child.on('close', (code) => {
      if (timer) clearTimeout(timer);
      if (settled) return;
      settled = true;
      resolve({ code: timedOut ? null : code, stdout, stderr, timedOut });
    });
  });
}

// Tier 2: executes caller-supplied commands (the target's own test/lint/
// build command) through a filtered child environment. Every command in
// this call is bound to the SAME snapshotHash, captured once before the
// first command runs.
async function runTier2({ cd, commands, timeout, envMode, envPassthrough }, spawnOpts = {}) {
  const snapshotHash = await computeSnapshotHash(cd);
  const env = buildChildEnv({ envMode, envPassthrough });
  const results = [];
  for (const command of commands) {
    const startedAt = new Date().toISOString();
    const startedAtMs = Date.now();
    const before = await contentState(cd);
    const result = await runWithTimeout(command, { cd, env, timeout }, spawnOpts);
    const after = await contentState(cd);
    results.push({
      command,
      startedAt,
      finishedAt: new Date().toISOString(),
      durationMs: Date.now() - startedAtMs,
      exitCode: result.code,
      timedOut: result.timedOut,
      touchedFiles: diffInventories(before, after),
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
  const snapshotHashAfter = await computeSnapshotHash(cd);
  return { snapshotHash, snapshotHashAfter, targetChanged: snapshotHashAfter !== snapshotHash, results };
}

// Content hash of every file that differs from HEAD or is untracked under cd (git), or of every
// file (plain folder). Comparing two of these shows what a command wrote, including re-edits of
// an already-dirty file. Gitignored output is not covered.
async function contentState(cd) {
  if (!(await isGitRepo(cd))) return (await hashInventory(cd)).files;
  const [changed, untracked] = await Promise.all([
    runCapture('git', ['diff', 'HEAD', '--name-only', '--relative', '-z', '--', '.'], cd),
    runCapture('git', ['ls-files', '--others', '--exclude-standard', '-z'], cd),
  ]);
  const paths = new Set([
    ...changed.stdout.toString('utf8').split('\0'),
    ...untracked.stdout.toString('utf8').split('\0'),
  ].filter((p) => p.length > 0 && !p.endsWith('/')));
  const state = {};
  for (const rel of [...paths].sort()) {
    try {
      state[rel] = await sha256OfFile(path.join(cd, rel));
    } catch (err) {
      state[rel] = err.code === 'ENOENT' ? 'deleted' : `unreadable: ${err.code || err.message}`;
    }
  }
  return state;
}

const FETCH_TIMEOUT_MS = 120000;

async function gitLine(args, cwd) {
  const r = await runCapture('git', args, cwd);
  return r.code === 0 ? r.stdout.toString('utf8').trim() : null;
}

async function revCount(range, cwd) {
  const out = await gitLine(['rev-list', '--count', range], cwd);
  return out === null ? null : Number(out);
}

// No prompt and a hard time limit: an expired token must fail, not hang the review.
function gitFetch(cwd) {
  return new Promise((resolve) => {
    const env = { ...process.env, GIT_TERMINAL_PROMPT: '0', GCM_INTERACTIVE: 'never' };
    const child = spawn('git', ['fetch', '--quiet'], { cwd, env, shell: false, timeout: FETCH_TIMEOUT_MS });
    let stderr = '';
    child.stderr.on('data', (d) => { stderr += d.toString('utf8'); });
    child.on('error', (err) => resolve({ ok: false, error: err.message }));
    child.on('close', (code, signal) => {
      if (code === 0) resolve({ ok: true, error: null });
      else resolve({ ok: false, error: signal ? `killed by ${signal} after ${FETCH_TIMEOUT_MS / 1000} s` : stderr.trim() || `exit ${code}` });
    });
  });
}

// Branch, HEAD and how far HEAD is behind its upstream and origin/HEAD: raw git facts only.
async function repoFreshness(dir, { role, fetch = false }) {
  const abs = path.resolve(dir);
  try {
    if (!(await stat(abs)).isDirectory()) throw new Error('not a directory');
  } catch (err) {
    throw new RelayError(`--${role === 'cd' ? 'cd' : 'repo'} "${abs}" is not an accessible directory: ${err.message}`);
  }
  if (!(await isGitRepo(abs))) return { path: abs, role, gitRepo: false };
  const record = { path: abs, role, gitRepo: true, fetched: false };
  if (fetch) {
    const f = await gitFetch(abs);
    record.fetched = f.ok;
    if (!f.ok) record.fetchError = f.error;
  }
  const branch = await gitLine(['rev-parse', '--abbrev-ref', 'HEAD'], abs);
  record.branch = branch === 'HEAD' ? null : branch;
  record.head = await gitLine(['rev-parse', 'HEAD'], abs);
  record.headDate = await gitLine(['log', '-1', '--format=%cI', 'HEAD'], abs);
  const status = await gitLine(['status', '--porcelain', '--', '.'], abs);
  record.dirty = status === null ? null : status.length > 0;
  record.upstream = await gitLine(['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{upstream}'], abs);
  record.ahead = record.upstream ? await revCount('@{upstream}..HEAD', abs) : null;
  record.behind = record.upstream ? await revCount('HEAD..@{upstream}', abs) : null;
  record.defaultBranch = await gitLine(['symbolic-ref', '--quiet', '--short', 'refs/remotes/origin/HEAD'], abs);
  record.behindDefault = record.defaultBranch ? await revCount(`HEAD..${record.defaultBranch}`, abs) : null;
  const fetchHead = await gitLine(['rev-parse', '--git-path', 'FETCH_HEAD'], abs);
  record.lastFetchedAt = null;
  if (fetchHead) {
    try {
      record.lastFetchedAt = (await stat(path.resolve(abs, fetchHead))).mtime.toISOString();
    } catch {
      // Never fetched: no FETCH_HEAD file, lastFetchedAt stays null.
    }
  }
  return record;
}

const ARTIFACT_MAX_BYTES = 2 * 1024 * 1024;
const MAX_ARTIFACT_FILES = 50;
const ARTIFACT_READ_CONCURRENCY = 16;
const WALK_SKIP = new Set(['.git', 'node_modules']);

// A past run's findings file or findings.json inside a target makes its real claim IDs "target
// text", so the scan's target-derived exemption could pass a real leak of those IDs. Match real
// review output only: a seat header, a claim heading with a dash plus a Severity line, or a
// findings.json with both origins and final_state. The protocol's own schema example is skipped.
function looksLikeReviewOutput(text) {
  if (/^# Shared Review Protocol\b/.test(text)) return false;
  if (/^# Seat [AB] findings\b/m.test(text)) return true;
  if (/^#{2,3} [AB]\d+ [—–-] /m.test(text) && /^Severity: /m.test(text)) return true;
  return /"origins"\s*:\s*\[\s*"[AB]\d+"/.test(text) && /"final_state"\s*:/.test(text);
}

// Lazy, so the scan below can stop walking a large plain folder once it has enough hits.
async function* walkFileNames(root, rel = '') {
  for (const d of await readdir(path.join(root, rel), { withFileTypes: true })) {
    const relPath = rel ? path.join(rel, d.name) : d.name;
    if (d.isDirectory()) {
      if (!WALK_SKIP.has(d.name)) yield* walkFileNames(root, relPath);
    } else if (d.isFile()) {
      yield relPath;
    }
  }
}

async function listTargetFiles(dir) {
  if (await isGitRepo(dir)) {
    const r = await runCapture('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], dir);
    return r.stdout.toString('utf8').split('\0').filter((p) => p.length > 0 && !p.endsWith('/'))[Symbol.iterator]();
  }
  return walkFileNames(dir);
}

// Reads with bounded concurrency and stops listing and reading once MAX_ARTIFACT_FILES are found;
// capped:true then says the count is a lower bound.
async function findReviewArtifacts(dir, list = listTargetFiles) {
  const names = await list(dir);
  const found = [];
  let exhausted = false;
  // Workers take names one at a time from the shared iterator (git list or lazy folder walk).
  const take = async () => {
    const r = await names.next();
    if (r.done) exhausted = true;
    return r.done ? null : r.value;
  };
  const worker = async () => {
    while (!exhausted && found.length < MAX_ARTIFACT_FILES) {
      const rel = await take();
      if (rel === null) break;
      try {
        const full = path.join(dir, rel);
        const st = await stat(full);
        if (!st.isFile() || st.size > ARTIFACT_MAX_BYTES) continue;
        const text = await readFile(full, 'utf8');
        if (!text.includes('\0') && looksLikeReviewOutput(text)) found.push(rel.split(path.sep).join('/'));
      } catch {
        // Deleted or unreadable between listing and reading: nothing to report for it.
      }
    }
  };
  await Promise.all(Array.from({ length: ARTIFACT_READ_CONCURRENCY }, worker));
  // Stopped early with names left unread: the count is only a lower bound.
  const capped = !exhausted && !(await names.next()).done;
  if (typeof names.return === 'function') await names.return();
  return { count: found.length, files: [...found].sort().slice(0, MAX_ARTIFACT_FILES), capped };
}

// Each watch file goes to the most specific --cd/--repo that contains it; for that repo, counts the
// commits on its upstream and origin/HEAD (when behind) that touch the file.
async function watchUpstreamChanges(records, watchFiles) {
  const outside = [];
  for (const file of watchFiles) {
    const abs = path.resolve(file);
    const owner = records
      .filter((r) => r.gitRepo && r.head)
      .map((r) => ({ r, rel: path.relative(r.path, abs) }))
      .filter(({ rel }) => rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel))
      .sort((a, b) => b.r.path.length - a.r.path.length)[0];
    if (!owner) {
      outside.push(abs);
      continue;
    }
    const { r, rel } = owner;
    r.watchedChangedUpstream ??= [];
    const gitRel = rel.split(path.sep).join('/');
    const refs = [];
    if (r.behind > 0) refs.push(r.upstream);
    if (r.behindDefault > 0 && r.defaultBranch !== r.upstream) refs.push(r.defaultBranch);
    for (const ref of refs) {
      const log = await gitLine(['log', '--format=%h', `HEAD..${ref}`, '--', gitRel], r.path);
      const commits = log ? log.split('\n').filter(Boolean).length : 0;
      if (commits > 0) {
        // The same change can reach HEAD through another merge: commits differ, content does not.
        const diff = await runCapture('git', ['diff', '--quiet', 'HEAD', ref, '--', gitRel], r.path);
        r.watchedChangedUpstream.push({ file: gitRel, ref, commits, contentDiffers: diff.code === 1 ? true : diff.code === 0 ? false : null });
      }
    }
  }
  return outside;
}

function freshnessWarnings(records) {
  const lines = [];
  for (const r of records) {
    if (r.reviewArtifactCount > 0) {
      lines.push(`preflight: WARNING: ${r.reviewArtifactCount}${r.reviewArtifactCountIsLowerBound ? '+' : ''} file(s) in ${r.path} ` +
        `hold review output with real claim IDs (seat headers, claim blocks or findings.json), e.g. ${r.reviewArtifactFiles[0]}`);
    }
    for (const w of r.watchedChangedUpstream ?? []) {
      if (w.contentDiffers === false) {
        lines.push(`preflight: note: ${w.file} in ${r.path} has ${w.commits} commit(s) on ${w.ref} not in HEAD, but its content is identical to HEAD`);
      } else {
        lines.push(`preflight: WARNING: ${w.file} in ${r.path} changed in ${w.commits} commit(s) on ${w.ref} not in HEAD and differs from HEAD`);
      }
    }
    if (r.behind > 0) lines.push(`preflight: WARNING: ${r.path} is ${r.behind} commit(s) behind ${r.upstream}`);
    if (r.behindDefault > 0 && r.defaultBranch !== r.upstream) {
      lines.push(`preflight: WARNING: ${r.path} is ${r.behindDefault} commit(s) behind ${r.defaultBranch}`);
    }
    if (r.fetchError) lines.push(`preflight: WARNING: git fetch failed in ${r.path}: ${r.fetchError}`);
  }
  return lines;
}

// Re-checks whether a previously-captured snapshotHash still matches the
// target's CURRENT state. A caller uses this before citing old Tier 2 (or
// Tier 1) evidence as current -- stale evidence must never be presented as
// describing content it no longer describes. Never mutates or interprets
// the evidence; only reports match/mismatch as a fact.
async function checkStale(cd, snapshotHash) {
  const current = await computeSnapshotHash(cd);
  return { stale: current !== snapshotHash, currentSnapshotHash: current };
}

async function run(args) {
  const cdAbs = path.resolve(args.cd);
  let cdStat;
  try {
    cdStat = await stat(cdAbs);
  } catch (err) {
    throw new RelayError(`--cd "${cdAbs}" does not exist or is not accessible: ${err.message}`);
  }
  if (!cdStat.isDirectory()) {
    throw new RelayError(`--cd "${cdAbs}" is not a directory`);
  }

  const clearedLogs = args.compact ? await clearOwnLogs(args.logDir) : [];
  // A plain folder is hashed file by file; do it once for Tier 1 and the snapshot hash.
  const inventory = (await isGitRepo(cdAbs)) ? null : await hashInventory(cdAbs);
  const tier1 = await runTier1(cdAbs, inventory);

  let snapshotHash = await computeSnapshotHash(cdAbs, inventory);
  let tier2 = null;
  if (args.exec.length > 0) {
    tier2 = await runTier2({
      cd: cdAbs,
      commands: args.exec,
      timeout: args.timeout,
      envMode: args.envMode,
      envPassthrough: args.envPassthrough,
    });
    // Tier 1 and Tier 2 are computed from the same pre-command git state in
    // a single invocation (Tier 1 runs, then Tier 2's own snapshotHash is
    // captured immediately before its first --exec command) -- both must
    // agree, since nothing in this process mutates the target between them.
    snapshotHash = tier2.snapshotHash;
    if (args.compact) tier2 = await compactTier2(tier2, args);
  }

  const repos = [await repoFreshness(cdAbs, { role: 'cd', fetch: args.fetch })];
  for (const repo of args.repos ?? []) repos.push(await repoFreshness(repo, { role: 'repo', fetch: args.fetch }));
  const outside = await watchUpstreamChanges(repos, args.watchFiles ?? []);
  for (const r of repos) {
    const artifacts = await findReviewArtifacts(r.path);
    if (artifacts.count > 0) {
      r.reviewArtifactCount = artifacts.count;
      r.reviewArtifactFiles = artifacts.files;
      if (artifacts.capped) r.reviewArtifactCountIsLowerBound = true;
    }
  }

  const result = { tier1: args.compact ? await compactTier1(tier1, args) : tier1, tier2, snapshotHash, repos };
  if (outside.length > 0) result.watchFilesOutsideRepos = outside;
  if ((args.sourceSnapshots ?? []).length > 0) result.sourceSnapshots = await recordSourceSnapshots(args.sourceSnapshots);
  if (clearedLogs.length > 0) result.clearedEarlierLogs = clearedLogs.sort();
  return result;
}

// A plain export (git archive) of another repository has no git metadata, so its origin is
// recorded as stated and its bytes are pinned by a content-hash inventory.
async function recordSourceSnapshots(snapshots) {
  const out = [];
  for (const s of snapshots) {
    const abs = path.resolve(s.dir);
    let st;
    try {
      st = await stat(abs);
    } catch (err) {
      throw new RelayError(`--source-snapshot folder "${abs}" does not exist or is not accessible: ${err.message}`);
    }
    if (!st.isDirectory()) throw new RelayError(`--source-snapshot "${abs}" is not a directory`);
    // Python caches left by an earlier test run are not source; they would change the hash with no source change.
    const inventory = await hashInventory(abs, { skipCaches: true });
    const rec = { path: abs, repo: s.repo, ref: s.ref, fileCount: Object.keys(inventory.files).length, snapshotHash: inventory.snapshotHash };
    if (inventory.skippedCaches.length > 0) {
      rec.skippedCacheCount = inventory.skippedCaches.length;
      rec.skippedCaches = inventory.skippedCaches.slice(0, 20);
    }
    out.push(rec);
  }
  return out;
}

const OWN_LOG_RE = /^(command-\d+\.std(out|err)\.log|tier1\.diff)$/;

// A rerun into the same --log-dir replaces this script's own earlier logs (a stale command-3 log
// from a longer earlier run would otherwise look like current evidence); other files stay.
async function clearOwnLogs(logDir) {
  const dir = path.resolve(logDir);
  let names = [];
  try {
    names = await readdir(dir);
  } catch (err) {
    if (err.code === 'ENOENT') return [];
    throw err;
  }
  const removed = names.filter((n) => OWN_LOG_RE.test(n));
  for (const n of removed) await rm(path.join(dir, n), { force: true });
  return removed;
}

// The Tier 1 diff can be as large as the whole change under review; seats read it from the log or git.
async function compactTier1(tier1, { logDir }) {
  if (!tier1.gitRepo) return tier1;
  const dir = path.resolve(logDir);
  await mkdir(dir, { recursive: true });
  const diffLog = path.join(dir, 'tier1.diff');
  await writeFile(diffLog, tier1.diff, 'utf8');
  const { diff, ...rest } = tier1;
  return {
    ...rest,
    diff: { bytes: Buffer.byteLength(diff, 'utf8'), sha256: sha256(Buffer.from(diff, 'utf8')), log: diffLog },
  };
}

function streamSummary(text, tailLines) {
  const lines = text.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  const matches = lines.filter(isSignalLine);
  return {
    bytes: Buffer.byteLength(text, 'utf8'),
    sha256: sha256(Buffer.from(text, 'utf8')),
    lineCount: lines.length,
    tail: tailLines > 0 ? lines.slice(-tailLines) : [],
    summary: lines.filter((l) => SUMMARY_RE.test(l)).slice(-MAX_MATCH_LINES),
    matches: matches.slice(0, MAX_MATCH_LINES),
    matchesTruncated: matches.length > MAX_MATCH_LINES,
  };
}

// Full streams go to --log-dir; the JSON keeps only what a reader needs to judge and verify them.
async function compactTier2(tier2, { logDir, tail }) {
  const dir = path.resolve(logDir);
  await mkdir(dir, { recursive: true });
  const results = [];
  for (const [i, r] of tier2.results.entries()) {
    const stdoutLog = path.join(dir, `command-${i + 1}.stdout.log`);
    const stderrLog = path.join(dir, `command-${i + 1}.stderr.log`);
    await writeFile(stdoutLog, r.stdout, 'utf8');
    await writeFile(stderrLog, r.stderr, 'utf8');
    const { stdout, stderr, ...rest } = r;
    results.push({
      ...rest,
      stdout: { ...streamSummary(stdout, tail), log: stdoutLog },
      stderr: { ...streamSummary(stderr, tail), log: stderrLog },
    });
  }
  return { snapshotHash: tier2.snapshotHash, snapshotHashAfter: tier2.snapshotHashAfter, targetChanged: tier2.targetChanged, compact: true, results };
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0) printUsageAndExit(0);
  let args;
  try {
    args = parseArgs(argv);
  } catch (err) {
    if (err instanceof RelayError) {
      // The error goes last and alone: the full help would scroll it off the screen.
      process.stderr.write(`Run with --help for every option.\npreflight.mjs: ${err.message}\n`);
      process.exit(2);
    }
    throw err;
  }
  try {
    if (args.checkStale !== null) {
      const cdAbs = path.resolve(args.cd);
      const result = await checkStale(cdAbs, args.checkStale);
      process.stdout.write(JSON.stringify(result, null, 2) + '\n');
      process.exit(result.stale ? 1 : 0);
    }
    const result = await run(args);
    for (const line of freshnessWarnings(result.repos)) process.stderr.write(`${line}\n`);
    for (const s of result.sourceSnapshots ?? []) {
      if (s.skippedCacheCount) {
        process.stderr.write(
          `preflight: WARNING: ${s.path} holds ${s.skippedCacheCount} Python cache item(s) (${s.skippedCaches.slice(0, 3).join(', ')}` +
            `${s.skippedCacheCount > 3 ? ', ...' : ''}); left out of its snapshotHash. Something ran Python in the snapshot; use "python -B" there.\n`
        );
      }
    }
    const text = JSON.stringify(result, null, 2) + '\n';
    if (args.out) {
      await writeFile(args.out, text, 'utf8');
    } else {
      process.stdout.write(text);
    }
  } catch (err) {
    if (err instanceof RelayError) {
      process.stderr.write(`preflight.mjs: ${err.message}\n`);
      process.exit(1);
    }
    throw err;
  }
}

const isDirectRun =
  typeof process.argv[1] === 'string' &&
  import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) {
  main().catch((err) => {
    process.stderr.write(`preflight.mjs: unexpected failure: ${err.stack || err}\n`);
    process.exit(1);
  });
}

export { parseArgs, runTier1, runTier2, computeSnapshotHash, checkStale, run, compactTier2, RelayError, runCapture, isGitRepo, repoFreshness, freshnessWarnings, findReviewArtifacts };
